Página de listagem com simulados criada
rbarrosodev/simuladao_oab pull request #5
Opened 2020-04-06 22:38 UTC by rbarrosogit

![screencapture-localhost-3000-simulados-2020-04-06-19_29_40](https://user-images.githubusercontent.com/61697765/78611826-332b4280-783e-11ea-8994-52e34562cb7e.png)
- [x] Scaffold da listagem criado
- [x] Template para a página de listagem das provas adicionado
- [ ] Validar as informações da prova com presence e uniqueness

2020-04-06 22:40 UTC, rbarrosogit commented
Seria mais interessante usar essa forma linear para a apresentação das provas ou um card seria mais apresentável?

2020-04-07 12:50 UTC, andcalazans commented
> Seria mais interessante usar essa forma linear para a apresentação das provas ou um card seria mais apresentável?

Nesse primeiro momento pode ser uma listagem mesmo, sem problemas

2020-04-07 12:51 UTC, andcalazans commented
Uma coisa é: Scaffold não se usa na vida real. O ideal é criar na mão mesmo de acordo com a demanda, por exemplo: Tem método pra tudo no controller que a gente nem sabe se vai ser usado. Ideal que seja tudo removido e seja adicionado apenas os códigos que existem necessidade, nesse caso: Index

2020-04-07 12:55 UTC, andcalazans requested changes

2020-04-07 12:55 UTC, andcalazans commented on app/helpers/simulados_helper.rb
> +module SimuladosHelper
Esse arquivo de helper só precisa ser criado quando for utilizado

2020-04-07 12:55 UTC, andcalazans commented on app/views/simulados/index.json.jbuilder
> +json.array! @simulados, partial: "simulados/simulado", as: :simulado
O que esse arquivo faz?

2020-04-07 12:55 UTC, andcalazans commented on db/migrate/20200406202302_create_simulados.rb
> +      t.string :title
Quais campos são obrigatórios? Se tiver alguma coisa obrigatória, não esqueça de informar na `migration`

2020-04-07 12:55 UTC, andcalazans commented on test/controllers/simulados_controller_test.rb
> +require 'test_helper'
O que esse arquivo faz? Precisamos ter ele nesse momento?

2020-04-07 18:19 UTC, rbarrosogit commented
-  [x] Arquivos desnecessários criados pelo scaffold removidos
-  [x] Criação de 2 partials para a implementação da navbar, uma para a home e outra para o index e show de simulados

2020-04-07 19:06 UTC, rbarrosogit commented
* Validações adicionadas
  * Título, tema, descrição e questões da prova são itens obrigatórios (presence: true)
  * Título obrigatoriamente único

2020-04-07 22:27 UTC, rbarrosogit commented
-  [x] Controller do model Simulado agora só contém o método index
-  [x] Validações da migration corrigidas (antes presence, agora null: false) 
-  [x] Chave "question" removida do model Simulado (sem uso no momento)

2020-04-07 22:36 UTC, rbarrosogit commented
* Métodos do commit acima removidos por terem sido criados pelo scaffold e não terem uso no momento.

2020-04-08 20:31 UTC, rbarrosogit commented
* Cabeçalho desnecessário e duplicado do HTML em views agora no application.html.erb
* "</i>" duplicado em algumas linhas de código foram removidos
* Partials de navbars diferentes excluídos
* Navbar default adicionada ao application.html.erb
* Gem do Font-Awesome adicionada e instalada, pois ao remover o cabeçalho HTML contendo a CDN do Font-Awesome causava a falha do Font-Awesome

2020-04-08 20:40 UTC, andcalazans approved these changes

2020-04-08 20:40 UTC, andcalazans commented on app/views/simulados/index.html.erb
> +          <h1 class="display-4"><i class="fas fa-gavel text-primary"></i></i> Simulados</h1>
`</i>` essas tags não estão corretas

2020-04-08 20:40 UTC, merged